version: "3.5"
services:
  backend:
    image: "rhub/ubuntu-gcc"
    tty: true
    command: bash
    volumes:
      - ../.:/data
    ports:
      - "5002:5002"
  web:
    image: nginx
    ports:
      - "5001:80"
    volumes:
      - ./nginx/www:/var/www
    environment:
      - NGINX_PORT=80
